pipeline {
  agent any
  stages {
    stage('Git Checkout') {
      steps {
        git credentialsId: 'git_creds', url: 'https://github.com/IovetsNikolay/terraform_final_task'
      }
    }
    stage('Check Dir') {
      steps {
        sh 'ls -a'
      }
    }
    stage('Chenge Dir') {
      steps {
        sh 'cd jenkins_terraform'
      }
    }

//    stage('Terraform Init') {
//      steps {
//        sh 'terraform init'
//      }
//    }
//    stage('Terraform Apply') {
//      steps {
//        sh 'terraform apply --auto-approve'
//      }
//    }


  }
}